### ISSUE TITLE
GLFW-b-1.4.7.1 test suite failure

### ISSUE THREAD

**Issue by peti** [bsl/GLFW-b#50]
Citing from http://hydra.cryp.to/build/618569/log/raw:

    Running 1 test suites...
    Test suite main: RUNNING... 
    main: user error (Pattern match failure in do expression at Test.hs:27:5-8)
    Test suite main: FAIL

**Comment by schell** [comment]
Tests are now compiling and passing.

**Comment by svmhdvn** [comment]
Just tried building on master and it still seems to be failing with the same message, should this issue be reopened?

**Comment by Mokosha** [comment]
The original link is broken can you provide a bit more context? (OS, GHC version, etc?)

**Comment by svmhdvn** [comment]
On NixOS 20.09 unstable, GHC 8.8.3, building locally with cabal 3.0.1.0.

**Comment by Mokosha** [comment]
This is likely happening because the underlying call to [`glfwInit`](https://www.glfw.org/docs/3.3/group__init.html#ga317aac130a235ab08c6db0834907d85e) failed. The tests need to be run in an environment where there is a way to open a rendering context in a new window.
