### ISSUE TITLE
Provide API to query window hints

### ISSUE THREAD

**Issue by Gabriel439** [bsl/GLFW-b#56]
Older versions of `GLFW-b` used to provide a `getWindowValue` function to query things like alpha bits, stencil bits, aux buffers, etc. (i.e. basically everything that the new API calls `WindowHints`).  Right now it seems like you can only set these options but you can no longer query them and I wanted to ask if you could provide an API for querying them.

I ran into this issue when trying to fix `gloss` to build against newer versions of `GLFW-b`

**Comment by schell** [comment]
Sure @Gabriel439, I'll check that out - I've been meaning to get some time to update the lib.

**Comment by schell** [comment]
@Gabriel439 - it looks like that specific functionality was removed from glfw in version 3. http://www.glfw.org/docs/latest/group__window.html#gacccb29947ea4b16860ebef42c2cb9337
So we don't have access to the framebuffer queries like we used to - but the other attributes are already covered in the various getWindowXXX functions.

**Comment by Gabriel439** [comment]
That's fine.  In this case, `gloss` was only using them to dump debug information about `glfw`'s state, so it's not a huge omission.  Thanks for looking into this!
