### ISSUE TITLE
HUnit 1.3 support

### ISSUE THREAD

**Issue by bergmark** [bsl/GLFW-b#62]
The latest (HUnit-1.3.1.1) is not supported by the GLFW-b test-suite so it has been disabled in stackage. When a fix is published to hackage please send a PR to re-enable this  to stackage (it's in the skipped-tests section) or ping me.

**Comment by JavierJF** [comment]
Hi. @bergmark  thanks for the advice! I'm going to put this in the next version, together with some fixes. You will get that PR in several days I hope.

**Comment by JavierJF** [comment]
@bergmark This is already solved in latest version! Thanks for the report and sorry about the delay! Hope we can be soon in stackage.
