### ISSUE TITLE
GL_SHADING_LANGUAGE_VERSION glGetString

### ISSUE THREAD

**Issue by joe9** [bsl/GLFW-b#63]
Hello,

Just want to check on how to do this when using GLFW-b? I could find getVersion and getVersionString. But, nothing for getting the Shading Language version.

printf("Supported GLSL is %s\n", (const char*)glGetString(GL_SHADING_LANGUAGE_VERSION));

Thanks

**Comment by cloudhead** [comment]
GLFW doesn't expose these functions, but you can always go directly to GL:

```
import           Graphics.GL
import           Foreign.C.String
import           Foreign.Ptr
...
cs <- castPtr <$> glGetString GL_SHADING_LANGUAGE_VERSION
putStrLn =<< peekCString cs
```

**Comment by joe9** [comment]
Thanks.
