### ISSUE TITLE
Building in windows with stack

### ISSUE THREAD

**Issue by machinedgod** [bsl/GLFW-b#67]
Hi,
I am having problems building the GLFW-b via stack in Windows. It builds just fine on Linux machine.
I am not entirely sure this is a GLFW-b problem, but any help or guidance in the right direction is very appreciated.

The log is a screenshot because its running in VM
![2016-12-12-133458_1179x871_scrot](https://cloud.githubusercontent.com/assets/5933618/21111505/e01797ee-c06f-11e6-87b6-8b161705b543.png)

**Comment by cloudhead** [comment]
See: https://github.com/bsl/bindings-GLFW/issues/48

**Comment by machinedgod** [comment]
Appreciated, sir!
