### ISSUE TITLE
GLFW 3.2 Support

### ISSUE THREAD

**Issue by scalanoob** [bsl/GLFW-b#69]
Is GLFW version 3.2 in the pipeline? I am writing Vulkan API code, and at the moment the only function from 3.2 I would like is glfwCreateWindowSurface. This allows access to the framebuffer used by the display - otherwise only off-screen rendering is possible.

Andre

**Comment by cloudhead** [comment]
I've started work here: https://github.com/bsl/bindings-GLFW/pull/44 but haven't had much time lately.

It looks like we'll need to add a dependency to the vulkan package.

**Comment by Althar93** [comment]
Hello,

Is this work still ongoing and/or in need of contributors ? The last activity on the 3.2.1 branch seems to be from 11 months ago. According to the GLFW website v3.3 is well underway already.

Cheers,

**Comment by cloudhead** [comment]
Hey, yes if you want to base on top of my `3.2.1` branch, that is welcome. We need to bindings to vulkan, I'm guessing we can use https://github.com/expipiplus1/vulkan - but also not sure we want to be pulling it entirely, since we only need 3-4 functions.

**Comment by Althar93** [comment]
Thanks, I've already started looking at your 3.2.1 branch & getting a feel for what is missing. Got hold of the vulkan bindings the other day & compiled locally so I'll see what is actually needed.

**Comment by cloudhead** [comment]
Great, let me know how it goes. You can comment in my PR, or mention me in your own.

**Comment by Rotaerk** [comment]
I noticed GLFW 3.3 appears to be almost done.  At least, the progress bar on glfw.org is at 95%.  Just worth noting in case any 3.2 support is throw-away work once you start adding support for 3.3.

**Comment by OlivierSohn** [comment]
The master branch of https://github.com/bsl/bindings-GLFW now contains 3.2.1, hence I guess it would be possible to do 3.2.1 support here too!

**Comment by Mokosha** [comment]
There's a [new version](https://hackage.haskell.org/package/GLFW-b-3.2.1.0) on hackage that should have all of the 3.2 bindings implemented.
