### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by SwiftsNamesake** [bsl/GLFW-b#70]
Most callback types and their setter functions lack documentation.

**Comment by Lokathor** [comment]
Most of the entire module could do with more documentation. If I wrote it, should I pull from the dev branch or from master? Master seems to have the most recent updates.

**Comment by SwiftsNamesake** [comment]
@Lokathor Maybe you should ping the maintainers, I'm not one of them unfortunately. But I'm sure they'd appreciate your help.

**Comment by cloudhead** [comment]
Hey, yes we would love that, please pull from master.

**Comment by Lokathor** [comment]
Excellent. Going well so far, mostly adding short descriptions to each and then linking to the 3.1 version of the function in the official C documentation.

Question, do we want to re-arrange the export order so that related items show up closer to each other in the haddock?

**Comment by cloudhead** [comment]
Great. Yeah that would indeed make things nicer, though please do it in a separate commit.

**Comment by Lokathor** [comment]
Pull request in with all the added docs. Import order not changed at all yet, we can worry about that later. The fact that the entire package is exported as a single module makes it easy enough to Ctrl+F and find what you need anyway.

**Comment by SwiftsNamesake** [comment]
@cloudhead @Lokathor Should we close this issue then? Did @Lokathor pull his changes?

**Comment by Lokathor** [comment]
Yeah that pull request was merged, we can close here.

**Comment by SwiftsNamesake** [comment]
@Lokathor @cloudhead Closed.
