### ISSUE TITLE
New hackage and stackage version?

### ISSUE THREAD

**Issue by Lokathor** [bsl/GLFW-b#75]
A lot of documentation got added, but that update hasn't been pushed to Hackage or Stackage in a few months. Any chance we could get that put up as a version 1.4.8.2 (current is 1.4.8.1)

**Comment by Mokosha** [comment]
It seems to have been removed from Stackage due to build failures with GHC 8.2.1 as well.

**Comment by Mokosha** [comment]
Small ping.

The biggest thing that needed updating was the HUnit bounds, which got fixed a long time ago but never made it to hackage. This means the latest HUnit *on stackage* doesn't build with GLFW-b even though the package still builds. That is to say, all we need to do is upload a new build :)

**Comment by Mokosha** [comment]
Both hackage and stackage should be updated with working packages.
