### ISSUE TITLE
Proposal : use strict data fields

### ISSUE THREAD

**Issue by OlivierSohn** [bsl/GLFW-b#80]
Looking at `Graphics.UI.GLFW.Types`, I see that every `data` has lazy fields.

My understanding of performance optimization wrt lazy / strict fields is that if the field is cheap to compute, then it's best to use a strict field, because it won't be slower, less memory will be used, also because we can possibly pack it in the structure.

I think many `data`s could benefit from having strict fields because the fields fall in the "cheap to compute / can be unpacked" category.

Or is there a reason why we specifically need lazyness in some of them?

**Comment by Mokosha** [comment]
Closed with #81.
