### ISSUE TITLE
Error building GLFW-b on OpenBSD

### ISSUE THREAD

**Issue by Mjnd** [bsl/GLFW-b#82]
Hi,

I tried to build the bindings of GLFW for Haskell on my machine that run OpenBSD/amd64 v6.3, but I had troubles completing the procedure; here the log for bindings-GLFW:

$ cabal install bindings-GLFW
Resolving dependencies...
Downloading bindings-DSL-1.0.25...
Configuring bindings-DSL-1.0.25...
Building bindings-DSL-1.0.25...
Installed bindings-DSL-1.0.25
Downloading bindings-GLFW-3.2.1.1...
Configuring bindings-GLFW-3.2.1.1...
Building bindings-GLFW-3.2.1.1...
Failed to install bindings-GLFW-3.2.1.1
Build log (/home/manuel/.cabal/logs/ghc-8.2.2/bindings-GLFW-3.2.1.1-4CzYP9nlXrfJkw6ue0vpOp.log):
cabal: Entering directory '/home/manuel/.cabal/tmp/cabal-tmp-89533/bindings-GLFW-3.2.1.1'
Configuring bindings-GLFW-3.2.1.1...
Preprocessing library for bindings-GLFW-3.2.1.1..
dist/build/Bindings/GLFW_hsc_make.o: In function `main':
dist/build/Bindings/GLFW_hsc_make.c:(.text+0x1b2): warning: strcpy() is almost always misused, please use strlcpy()
Building library for bindings-GLFW-3.2.1.1..
[1 of 1] Compiling Bindings.GLFW    ( dist/build/Bindings/GLFW.hs, dist/build/Bindings/GLFW.o )

In file included from glfw/src/context.c:28:0: error:

glfw/src/internal.h:33:11: error:
     fatal error: 'glfw_config.h' file not found
     #include "glfw_config.h"
              ^~~~~~~~~~~~~~~
   |
33 |  #include "glfw_config.h"
   |           ^
1 error generated.
`cc' failed in phase `C Compiler'. (Exit code: 1)
cabal: Leaving directory '/home/manuel/.cabal/tmp/cabal-tmp-89533/bindings-GLFW-3.2.1.1'
Updating documentation index /home/manuel/.cabal/share/doc/x86_64-openbsd-ghc-8.2.2/index.html
cabal: Error: some packages failed to install:
bindings-GLFW-3.2.1.1-4CzYP9nlXrfJkw6ue0vpOp failed during the building phase.
The exception was:
ExitFailure 1

I temporarily solved the above issue copying glfw_config.h from glfw/include/os/unix-like/ into glfw/include/GLFW inside the tarball, but I noticed inside bindings-GLFW.cabal that there is not support for OpenBSD (only Linux/FreeBSD), so I also want to request, please, if you can add support for OpenBSD to the GLFW bindings. But proceding to build GLFW-b I got this error:

$ cabal install GLFW-b
Resolving dependencies...
Downloading GLFW-b-3.2.1.0...
Configuring GLFW-b-3.2.1.0...
Building GLFW-b-3.2.1.0...
Failed to install GLFW-b-3.2.1.0
Build log (/home/manuel/.cabal/logs/ghc-8.2.2/GLFW-b-3.2.1.0-5DDe7ETkGHA7Z1dG5vqrBR.log ):
cabal: Entering directory '/home/manuel/.cabal/tmp/cabal-tmp-75226/GLFW-b-3.2.1.0'
Configuring GLFW-b-3.2.1.0...
Preprocessing library for GLFW-b-3.2.1.0..
Building library for GLFW-b-3.2.1.0..
[1 of 3] Compiling Graphics.UI.GLFW.Types ( Graphics/UI/GLFW/Types.hs, dist/build/Graphics/UI/GLFW/Types.o )
ghc: /home/manuel/.cabal/lib/x86_64-openbsd-ghc-8.2.2/bindings-GLFW-3.2.1.1-4CzYP9nlXrfJkw6ue0vpOp/HSbindings-GLFW-3.2.1.1-4CzYP9nlXrfJkw6ue0vpOp.o:
unknown symbol `_glfwPlatformGetCurrentContext'
ghc: unable to load package `bindings-GLFW-3.2.1.1'
cabal: Leaving directory '/home/manuel/.cabal/tmp/cabal-tmp-75226/GLFW-b-3.2.1.0'
cabal: Error: some packages failed to install:
GLFW-b-3.2.1.0-5DDe7ETkGHA7Z1dG5vqrBR failed during the building phase. The
exception was:
ExitFailure 1

I don't know how to fix this "unknown symbol" error...

Also, not an issue just taking advantage of the situation, out of my curiosity and my ignorance...
I noticed the GLFW bindings come with a bundled copy of the sources of the official GLFW, may I ask why the need to include the sources (and to build the GLFW library with the bindings)?
Would this mean that the GLFW library will be statically compiled automatically and included in any Haskell application using it and one won't have to care about installing separately the library in every system the application will be deployed? Great for portability!

Thank you very much.

**Comment by Mokosha** [comment]
Hi Mjnd. This seems to be an issue with [`bindings-GLFW`](https://github.com/bsl/bindings-GLFW) and not `GLFW-b`.

That being said -- I can address some of your questions here: First, yes, the sources a bundled to increase portability. It's mostly to reduce friction between typing "cabal/stack/whatever install" and actually having a working GLFW context. You can optionally get around that and use a system installation of GLFW by passing the `system-glfw` flag to cabal when building. This hasn't been tested recently so feel free to open a ticket on `bindings-GLFW` if it doesn't work.

With respect to adding OpenBSD support -- it might be as simple as placing whatever is in your `System.Info.os` value as an option in the conditional for linux in the cabal file. For example, on my Mac, I get:

    $ ghci
    > import System.Info as I
    > I.os
    "darwin"

I suspect you'll get something like `openbsd`, which you can add:

    if os(linux) || os(freebsd) || os(openbsd)
      include-dirs:
        ...

Regarding your missing symbols, it means that something was not included in the original compilation of the C-library for GLFW. This probably happened because you didn't match any of the conditionals in the cabal file that actually triggered the `c-sources` directive to build GLFW.

**Comment by Mjnd** [comment]
Thank you for the answers.

Is there a right way to include the above suggested edit in bindings-GLFW.cabal?

I extract $HOME/.cabal/packages/x86_64-openbsd-ghc-8.2.2/bindings-GLFW/3.2.1.1/bindings-GLFW-3.2.1.1.tar.gz, edit bindings-GLFW.cabal, recreate bindings-GLFW-3.2.1.1.tar.gz and overwrite $HOME/.cabal/packages/x86_64-openbsd-ghc-8.2.2/bindings-GLFW/3.2.1.1/bindings-GLFW-3.2.1.1.tar.gz

But the editings seems to be ignored (the package doesn't get downloaded again though, so my "version" should be picked up) and I also modified bindings-GLFW.cabal to be like this (and removing all the unneeded pieces) merging only the relevant parts:

---
library
  default-language: Haskell2010

  ghc-options: -Wall
  if impl(ghc >= 6.8)
    ghc-options: -fwarn-tabs

  exposed-modules:
    Bindings.GLFW

  build-tools:
    hsc2hs

  build-depends:
    base          < 5,
    bindings-DSL == 1.0.*

  include-dirs:
    glfw/include/GLFW
    glfw/include/os/unix-like
    glfw/include/
    glfw/src

  c-sources:
    glfw/src/context.c
    glfw/src/init.c
    glfw/src/input.c
    glfw/src/monitor.c
    glfw/src/window.c
    glfw/src/vulkan.c
    glfw/src/glx_context.c
    glfw/src/egl_context.c
    glfw/src/xkb_unicode.c
    glfw/src/linux_joystick.c
    glfw/src/posix_time.c
    glfw/src/posix_tls.c
    glfw/src/x11_init.c
    glfw/src/x11_monitor.c
    glfw/src/x11_window.c

  cc-options: -D_GLFW_USE_CONFIG_H
  cc-options: -DBINDINGS_GLFW_USE_X11

  extra-libraries:
    GL
    X11
    Xi
    Xrandr
    Xxf86vm
    Xcursor
    Xinerama
    pthread

  if flag(ExposeNative)
    cc-options: -DExposeNative
---

But the same error reappear and only if I copy glfw_config.h like before I can build GLFW-b that fails again with the same missing symbol. Sorry, I'm a newbie of cabal, before I restricted myself only on Haskell libraries pre-packaged for OpenBSD, so maybe I'm missing something about the internal workings of cabal.

Thank you again for your time and patience.

**Comment by Mjnd** [comment]
Thank you for your answers. bindings-GLFW now builds but I get this error for GLFW-b:

```
$ cabal install GLFW-b
Resolving dependencies...
Configuring GLFW-b-3.2.1.0...
Building GLFW-b-3.2.1.0...
Failed to install GLFW-b-3.2.1.0
Build log (/home/manuel/.cabal/logs/ghc-8.2.2/GLFW-b-3.2.1.0-5DDe7ETkGHA7Z1dG5vqrBR.log ):
cabal: Entering directory '/home/manuel/.cabal/tmp/cabal-tmp-61124/GLFW-b-3.2.1.0'
Configuring GLFW-b-3.2.1.0...
Preprocessing library for GLFW-b-3.2.1.0..
Building library for GLFW-b-3.2.1.0..
[1 of 3] Compiling Graphics.UI.GLFW.Types ( Graphics/UI/GLFW/Types.hs, dist/build/Graphics/UI/GLFW/Types.o )
ghc: /usr/X11R6/lib/libXcursor.a: unknown symbol `XRenderQueryExtension'
ghc: /usr/X11R6/lib/libXcursor.a: unknown symbol `XcursorSupportsARGB'
ghc:
/home/manuel/.cabal/lib/x86_64-openbsd-ghc-8.2.2/bindings-GLFW-3.2.1.1-4CzYP9nlXrfJkw6ue0vpOp/HSbindings-GLFW-3.2.1.1-4CzYP9nlXrfJkw6ue0vpOp.o:
unknown symbol `XcursorImageLoadCursor'
ghc: unable to load package `bindings-GLFW-3.2.1.1'
cabal: Leaving directory '/home/manuel/.cabal/tmp/cabal-tmp-61124/GLFW-b-3.2.1.0'
cabal: Error: some packages failed to install:
GLFW-b-3.2.1.0-5DDe7ETkGHA7Z1dG5vqrBR failed during the building phase. The
exception was:
ExitFailure 1
```
There is a port/package for OpenBSD of the official GLFW, so maybe the bundled version need some of their modifications from https://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/graphics/glfw/patches/ ?

Thank you againg for your time & patience.

**Comment by Mjnd** [comment]
It works!

I was able to build bindings-GLFW and GLFW-b flawlessly wih -f system-glfw and the addition of os(openbsd) in the cabal file, I wrote a fast and simple Main.hs where I init the library, I create a window and then terminate the library and the program compiled and ran flawlessly too, so I guess it really works.

Thank you again for your suggestion, your patience & your time.
