### ISSUE TITLE
crash on macOS when calling "terminate"

### ISSUE THREAD

**Issue by bkomuves** [bsl/GLFW-b#84]
Before exiting, according to the glfw docs I should call `terminate`. On macOS this crashes, with two different messages:

```
$ ./glfw_crash 
calling terminate
Segmentation fault: 11 
```

and

```
$ ./glfw_crash 
calling terminate
glfw_crash: internal error: stg_ap_p_ret
    (GHC version 8.0.2 for x86_64_apple_darwin)
    Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug
Abort trap: 6
```

macOS version: 10.13.2
GLFW-b version: 3.2.1.0
GHC version: 8.0.2

If I leave out the call to `terminate`, it seems to work ok. On Windows 7 and GHC 8.2.1 calling `terminate` works fine. 

Small example program reproducing the issue on my system is attached.

[glfw_crash.hs.txt](https://github.com/bsl/GLFW-b/files/3076080/glfw_crash.hs.txt)

**Comment by Mokosha** [comment]
Thanks for the report!

One way to check if this is a GLFW or GLFW-b bug is to see if a similar program written in C crashes with the same error message. Given that there are two competing error messages, there might be different causes for this behavior, one which is GHC specific and one which isn't. They could both be coming from some inappropriate way that GLFW handles state internally. Also, if it *does* crash using vanilla C-based GLFW then it might be useful to check if an up-to-date version of GLFW fixes this issue. 3.2.1 was a while ago.

**Comment by elmindreda** [comment]
The example seems to call `glfwTerminate` from callbacks, which is [not supported](https://www.glfw.org/docs/latest/intro.html#reentrancy).

**Comment by bkomuves** [comment]
Ah, I see. That kind of explains it (though calling it from a callback did
not cause an apparent issue on a different system). I will check what
happens if I restructure to code to avoid this when I get back to the macOS
machine. In any case, maybe this information should be added to the GLFW-b
haddocks?
