### ISSUE TITLE
waitEventsTimeout on OpenBSD behaves like pollEvents

### ISSUE THREAD

**Issue by Mjnd** [bsl/GLFW-b#89]
I've noticed the value I set on waitEventsTimeout is completely ignored, and the function returns immediately, irrespectively of any input, just like pollEvents. I can't install an updated version of GLFW or use an update version of GLFW-b because at the moment there is no GLFW 3.3.0 port for OpenBSD. Has the issue already been fixed? If so, can the fix be backported to GLFW-b v3.2.1.1?
Thank you.

Haskell bindings: GLFW-b v3.2.1.1
Operating System: OpenBSD/amd64 v6.7
GLFW library: GLFW v3.2.1 (2016-08-18)

**Comment by Mokosha** [comment]
Is this an issue with the C version of GLFW that's also present in GLFW-b, or is this an issue with GLFW-b? If it's the former, you'd need to take it up with the GLFW authors.

**Comment by Mjnd** [comment]
I use the system wide GLFW (I compile the library with cabal install -f system-glfw bindings-GLFW-...), because othewise bindings-GLFW doesn't compile. So, I think it's the latter.

**Comment by bsl** [comment]
I know it's troublesome, but could you write a very tiny test in C? If the GLFW C library function works like you expect, then clearly support is there, and we just messed up somewhere in the bindings. But if you can't make the C program act like you expect, then maybe the issue is that the GLFW C library doesn't make proper use of something in OpenBSD, or OpenBSD doesn't offer something that the author needed, etc.

If the C example doesn't work like you expect, then that's the perfect thing we'd want to provide to the GLFW C library author.

**Comment by Mjnd** [comment]
I managed to write a tiny test, and it behaves like expected: I can clearly see the behaviors is correct in all the three cases (glfwWaitEvents()/glfwWaitEventsTimeout()/glfwPollEvents). In glfwWaitEventsTimeout() the timeout is respected.

**Comment by Mjnd** [comment]
Is there any news? I moved to OpenBSD v6.8 but of course, still using the old libraries (there are no updates), the behavior is the same. Can I do something to help fixing the bug?

**Comment by Mokosha** [comment]
Unfortunately I don’t have OpenBSD so we’d have to figure out how to reproduce it somehow before we can debug it. Can you post the example program that works in C but not in Haskell?

**Comment by Mjnd** [comment]
Sorry for the bad quality of the code, I'm not fluent in C and I wrote the lines in a haste.

Here the Haskell version:

    import Control.Monad (unless)
    import qualified Graphics.UI.GLFW as GLFW

    main :: IO ()
    main = do
      _ <- GLFW.init

      GLFW.windowHint (GLFW.WindowHint'Resizable False)
      GLFW.windowHint (GLFW.WindowHint'ContextVersionMajor 2)
      GLFW.windowHint (GLFW.WindowHint'ContextVersionMinor 0)

      mwin <- GLFW.createWindow 640 480 "waitEventsTimeout" Nothing Nothing
      case mwin of

        Just win -> do
          GLFW.makeContextCurrent mwin

          GLFW.setErrorCallback $ Just showError
          GLFW.setKeyCallback win $ Just (handleKey)

          mainLoop win

          GLFW.destroyWindow win

        Nothing -> return ()

      GLFW.terminate

    mainLoop :: GLFW.Window -> IO ()
    mainLoop win = do
      a <- GLFW.windowShouldClose win
      unless a $ do

        tm <- GLFW.getTime
        case tm of
          Just v -> putStrLn $ (show v) ++ " seconds"
          Nothing -> putStrLn "No Time"

        GLFW.swapBuffers win
        GLFW.waitEventsTimeout 5

        mainLoop win

    showError :: GLFW.ErrorCallback
    showError e s = putStrLn $ unwords [show e, show s]

    handleKey :: GLFW.KeyCallback
    handleKey win (GLFW.Key'Q) _ _ _ = GLFW.setWindowShouldClose win True
    handleKey _ _ _ _ _ = return ()

The output for the first 5 seconds is:

    0.20587927 seconds
    0.254847067 seconds
    0.303944348 seconds
    0.357137818 seconds
    0.410336526 seconds
    0.46353705 seconds
    0.51675224 seconds
    0.569934396 seconds
    0.62313457 seconds
    0.676331881 seconds
    0.729531218 seconds
    0.782730275 seconds
    0.836012791 seconds
    0.889127761 seconds
    0.942329682 seconds
    0.995527063 seconds
    1.048729123 seconds
    1.101962611 seconds
    1.15512591 seconds
    1.20834578 seconds
    1.261522349 seconds
    1.314724409 seconds
    1.367919765 seconds
    1.421122104 seconds
    1.474318228 seconds
    1.527517774 seconds
    1.580717949 seconds
    1.633916727 seconds
    1.687115365 seconds
    1.740317425 seconds
    1.793515854 seconds
    1.846732441 seconds
    1.89991299 seconds
    1.953112746 seconds
    2.006312991 seconds
    2.05951107 seconds
    2.11270901 seconds
    2.165942987 seconds
    2.21910894 seconds
    2.272306111 seconds
    2.325505588 seconds
    2.378708207 seconds
    2.431905169 seconds
    2.485103737 seconds
    2.538308032 seconds
    2.59150234 seconds
    2.644700629 seconds
    2.697899686 seconds
    2.751098953 seconds
    2.804297661 seconds
    2.857497207 seconds
    2.910696544 seconds
    2.963896299 seconds
    3.017095007 seconds
    3.070294693 seconds
    3.123506531 seconds
    3.176708242 seconds
    3.22989368 seconds
    3.283089176 seconds
    3.336302131 seconds
    3.389491411 seconds
    3.442688443 seconds
    3.49592668 seconds
    3.549100385 seconds
    3.602285754 seconds
    3.655482855 seconds
    3.708688827 seconds
    3.761883344 seconds
    3.815084078 seconds
    3.868287605 seconds
    3.921481284 seconds
    3.974680411 seconds
    4.027879888 seconds
    4.081079294 seconds
    4.134277094 seconds
    4.187477059 seconds
    4.240676256 seconds
    4.293877129 seconds
    4.347073812 seconds
    4.40027252 seconds
    4.453487081 seconds
    4.506688094 seconds
    4.559870739 seconds
    4.613069796 seconds
    4.666268993 seconds
    4.71946784 seconds
    4.772666129 seconds
    4.826827722 seconds
    4.879066618 seconds
    4.932264139 seconds

Here the C version:

    #define GLFW_INCLUDE_NONE
    #include <GLFW/glfw3.h>
 
    #include <stdlib.h>
    #include <stdio.h>
 
    static void error_callback(int error, const char* description)
    {
        fprintf(stderr, "Error: %s\n", description);
    }

    static void key_callback(GLFWwindow* window, int key, int scancode, int action, int mods)
    {
        if (key == GLFW_KEY_ESCAPE && action == GLFW_PRESS) glfwSetWindowShouldClose(window, GLFW_TRUE);
    }
 
    int main(void)
    {
        GLFWwindow* window;
 
        glfwSetErrorCallback(error_callback);
 
        if (!glfwInit()) exit(EXIT_FAILURE);
 
        glfwWindowHint(GLFW_RESIZABLE, 0);
        glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 2);
        glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 0);
 
        window = glfwCreateWindow(640, 480, "glfwWaitEventsTimeout", NULL, NULL);
        if (!window) {
            glfwTerminate();
            exit(EXIT_FAILURE);
        }
 
        glfwSetKeyCallback(window, key_callback);
 
        glfwMakeContextCurrent(window);
        glfwSwapInterval(1);

        double time = 0;
 
        while (!glfwWindowShouldClose(window)) {
            time = glfwGetTime();
            printf("%f seconds\n", time);

            glfwSwapBuffers(window);
            glfwWaitEventsTimeout(5);
        }
 
        glfwDestroyWindow(window);
 
        glfwTerminate();
        exit(EXIT_SUCCESS);
    }

The output for the first 20 seconds is (I pressed some key around 10 s):

    0.203063 seconds
    0.251855 seconds
    6.953505 seconds
    9.715161 seconds
    9.756513 seconds
    9.821946 seconds
    9.863376 seconds
    9.912522 seconds
    9.961817 seconds
    10.010962 seconds
    10.091317 seconds
    10.132560 seconds
    10.197473 seconds
    10.238748 seconds
    10.287920 seconds
    16.994837 seconds
    19.260195 seconds
    19.366669 seconds

I also ran the test suite included in the GLFW-b package and the waitEventsTimeout test is passed.

**Comment by Mjnd** [comment]
Found the problem! I need to compile with -threaded.
Sorry, I know nothing of Parallell Haskell and I never needed that flag...
Sorry to have bothered you all, I'd been just stupid. Next time I will be more carefull.
Thank you for the support and the time I made you lost.

**Comment by Mokosha** [comment]
No need to apologize! Sometimes these things are difficult and unintuitive. I'm glad you found the problem! If there's a way that we can improve the documentation please let us know.

**Comment by bsl** [comment]
@Mjnd No problem, that's definitely not a "stupid" problem. I think you are being very adventurous and courageous to mess around with this stuff. Have fun and please come back if you run into other problems.

**Comment by Mjnd** [comment]
Thank you very much. I think I will definitely come back because I'm using GLFW and your bindings for a video game I'm writing, so using correctly your library is a fundamental part of the development and of the game.
(Of course I'm not saying your work is bad or full of bugs, because it is not, just I'm sure I'll need some new delucidation, or I'll spot some strange behaviour that I won't interpret correctly, or the like.)
About the documentation, I think a simple note between brackets about the need of the -threaded flag, in the description of waitEventsTimeout (and any other function needed it), will be sufficient.
