### ISSUE TITLE
Question about package distribution

### ISSUE THREAD

**Issue by wujilingfeng** [bsl/GLFW-b#91]
May I ask you a question?
I have c library named "viewer" which  depends glfw's includer file and other opengl basic libraries. In generally  It works with other libraries such as glfw for visualization.
I want create a package on haskell, but I don't konw how to write the .cabal file.
Of course，I can distribute the library ”viewer“ whick is written by c. but users have to download glfw of c language to use it.
 Do you have any good suggestions ？

**Comment by Mokosha** [comment]
Hi @wujilingfeng!

Unfortunately, it's hard to offer suggestions without seeing your code. If you read the README, there is a link to the [demo](https://github.com/bsl/GLFW-b-demo), which should serve as an example project using GLFW-b.
